//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRobot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyRobot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2BkYGD4DwQgGgR4mIBEaFBGZl6+c35ubn6ejkJYalFxZn6erZmeobGeoaWBqYWesbmhjoJzaU5JaVGqbV5qaUlRYo6OQkBpUk5msndqZUh+dmqerampkZGFYaqlebK5qampsQEryA5hsNF67qn5uaklRZV6vqnFGSxAcfYyiC1ciUXJGZllqcYpuZz5Bal5eaVFScUsKYkliSBFHBwcTCAHCqgzMNgA6bu5Jj2czEAGP4iwBxJMv+qZGIyZIZ75/Z+JQQTqsSdXrvu5v7wsuP8pg0Azo9IH3Z3SMX+A8r+ZIPIWEkCCA4gvyRrP2/vj6X9yaQY0sDKs+cDMP9IHQOzu19yOp67ecjj954IDA0ODPRLej4RRxGAxwwBmMDEzsrCxs3JwcXPy8PHzCgoICwsLCQqKiouIiIuKiSkAFXW8Sp3AyNDA4OAD1VhxK1rwWk3CMfmXzDwOG5hO2X193uR8PTvPfYZFj6/HnydXo/kMCgWk51uc0AOLyMy2nnj0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string armby {
            get {
                return ResourceManager.GetString("armby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJoFUN5A267zQrGipXjR4u5W3N29UJzi7l6sFHeKu7sVKe5QXIoVd3fXk/b7/pn/nJmTa5697zzZTbLh3d1kBgACAMALuP3VvxsSFFioKZuZ29iK2Fpb29rQEaubODia29rwcTAwszIwczOxczGwcjLTEYs4Wzk5O5jw2Zg4OzkYWNERKzobWpkbyZi4q9pamtjwsbOzsHAxm3BzGnGys7OzMsH8vcbbf6dmkDCxtTZxcnBnkDNxNHsF5uFc/nOV1wYORmbmLiasxtYItnYmNjbODoaOr4wNnAz+VoKHh4f6e4NolADAC+qSNVs4AjRoUP8WcJoAAHXvCwU8aPynMw8vUADGfzu2OT0rL7E39aZ9C0ALgLw/pW96p/MIHu/+b12uXvD2XoExScCa0Xq79fL/1WFwM7bsCNzw+sbr0CN4zFZ5Jmlo2GHjmp0/XbQuCPw/mxYUSrfS4EJXYZpQOy7CH2Hs/nnhIHcXEQD4IvC/ov1/xf+V+5+/DAD1r3wF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis1 {
            get {
                return ResourceManager.GetString("axis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bplVFbR1/a7b1Q6pVtJaekWaaW7pJHublC6U6RBWjoFpLu7u0O6u94N/+cZ5znvGO8558v5xvUbc89rzRXc7pu91xoMAQgAAA+gHvOjEKHAi6KckbGFpaClubmlBe0bJX0bW2NLC142ekZmekbO96wc9MzsjLRvBO3N7Oxt9Hkt9O3tbHTMaN/I2OuaGeuJ6zsrWJrqW/CysjIxcTDqc7LrsbOysjK/f/X4M9CflqYX1bc017ezcaaX1Lc1egnWYRz+81PgdWz0jIwd9Jm/msNZWulbWNjb6Nq+/Kpjp/M4CBYWFurxA6JSAgAPmOfNWULgXoAG5fFyygcAUNeeUMA/vv/8Y24eoACM//qHrY1NSolujaI1rgOo3hCSQ7q/+Oq3YH/Jf43lsAc/HhoYI4TMKfWX6w//p+zihZ0sPuPV5JAQSaHyJ+VjLQcWQe23L01KlfLkUqPxH4H/TRs1Cy3MlwitxDZfBCVL1gWUNl4JYjKcCALAN77/EY3/I/5v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis12 {
            get {
                return ResourceManager.GetString("axis12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJoFUBxB1653QxII7u4Owd0JTnCH4Brcg1twd3eX4O4S3CG4uxPcnTvh+7+q/96qO0+dft9zumdmd7aZnqkCBAaBQK/A9k//bbDvgEZZwcTUylrI2tLS2oqGUMXIzt7U2oqXjY6RmY6Rk4GVg46ZnZGGUMjB4oeDnRGvlZHDDzs9CxpCOQd9C1MDSSMXJWtzIyteVlYmJg5GI052A3ZWVlZmhg//zoHydmg6MSNrS6Mfdi500kb2Ju+BOqTjf84CrWdnYGLqaMRsaPnJ2sbIysrBTt/+vaHeD71/g6CgoN79+4CIFCAQD6ArlixhnyAAg/CvcRIDgd49eL0DmYv958s8vr4Dof7PF9uenpMRO5hC6tgBIfqCic9om3A0n4B+5v8Zy1ELfDxsICbxmDPa7nZe/3/aaUUtmslm8fsLFIu7KGfCF4f82GoPLOXfgpU8fTEOCV9A/88W7VzXtef2rhvCo7rL9LVeMOcGLCQLBSEMAv3k/1/R8b/i/6r995cB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis23 {
            get {
                return ResourceManager.GetString("axis23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tLt1UB5Bu+Y9QHB3dw3B3QkEgmvw4O7uGtyDB3eChuAS3N3dJQQI7m475D3nq/Nt1e5/O7/qvq6+7366e3p4ZgYqASAAAHgBj1d9PZAgwUpV2dzC1u6DnY2NnS0DmZqJo5OFna0gFxMrOxMrLwsnDxM7NysD2QcXa2cXRxNBWxMXZ0cDawYyRRdDawsjGRMPFTsrE1tBTk42Nh5WE15uI25OTk52FujXOTD/Dc0kYWJnY+Ls6MEkZ+Jk/gaMw7r+ZxYEA0cjcwtXE3ZjG3g7exNbWxdHQ6c3xgbOBq+d4ODgIF8XiEYLAAKgrtpwRMFDgQb1tUKRAgDIez9IAFLqPyfz8AIJYP3Xif2ZmZeX2JtGb98G0AIhKE4ZfxFqP4L5Icn/5HkEwOVhg2WKmD2r9Xb75f+kDYX7/FMM0R37VH8jJAIb3vPEG6xUpyp2eKUJKeUOVbwH/reDSyWnaw8xuYuwPLvrCkfjAx97sOgocb4oAHwR/h+l/X+U/1/sv68M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis34 {
            get {
                return ResourceManager.GetString("axis34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dNoFUBzB1ijg2RBCIEhwD8EJGtwhwd1dg0twdwju7hpcgru7e3AnuENwhzfh/rfqf6/q7Vdnzume7t6ldnt2tgoAAgDAM/j4l/894F+BB0U5YxMLS35Lc3NLC+qPSgY2tiaWFtwstPSMtPTsn5nZaBlZ6ak/8tub2dnbGHBbGNjb2eiYUX+Usdc1M9ETN3BWsPxuYMHNzMzAwEZvwM6qx8rMzMz4Gfrfc6C+LE0rbGBpbmBn40wraWBr/Brsh3H4z7PA6djoGZs4GDDqm8NaWhlYWNjb6Nq+1tex0/k36O3bt6/+vcD35ADABeZlc6ZQWCiwQPp3EBcDgFd3nq8AXrH//DH3z68AtP/5wzanZqWE9yaR27aA9z4Qor80DbgaD+B5mP8Zy9YAvjx8MCbwGdNbbrae/395eWVW4CDDqv031GZwBEfQF8a8vVO799/b4c+6HDzi478A/88D6kaC/1w+pfOrEW2nYMwe/5ByDt8PIIcPALx4/1e0/a/4v/r+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis45 {
            get {
                return ResourceManager.GetString("axis45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bplVB3Bu+7ZBAsuwSFogru7huAQ3D24BXcIECB4ILhLcHd3C+7B3d3dbif/c2aduWvdWfNlPg3Pb1U9T1e9G3Y1tbv3BgAIAACeQf31v0J8BXbKCqZm1jYiNlZWNta0xCpGdvZmNtZ87PRMLPRMXIxsnPQsHEy0xCKOlg6OdkZ81kaODnb6lrTEnxwNLM0MpYxclWwsjKz52NiYmTmZjLg4DDnY2NhYGKH/fo83/740vZiRjZWRg50rvYyRvSkUOA7r9J/vAq9vZ2hq5mTE8tkKzuaLkbW1o52BPdRnfQf9v0WvX79+9fcJolIAAC/oi1asoXCQYED52xWwA8CrO+9XQCr7fxZz//wKwPivhW1MTsuK7U6gtW4CqH4QpCd09fhaD+C88X/Vcr4Cn14tGMbfsqQ232w+/59c/SfnD+MZ5Ta/O/3ZWHs/wYScD7vOO0ptWLy/8x+8swSB/00ekrIdjBgaHayqzB023D+EuxkFhRkXGYUB4KvA/2it/6P9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis56 {
            get {
                return ResourceManager.GetString("axis56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bp1UFbR2/e77xuQ7u5OpQSlW+kSUCQF6W7pBkFEkO6SEpQGAekW6e4U6RRBmnfB83vOPOedec+cOTPnP76fWet7Xdde+773WsvN3nOPEAyCoGugG78RBhx0z9XMLWztpOxsbOxsH9C8MHF0srCzFXnMwc3DwS3A9Yifg4eP+wGNlIu1s4ujiYitiYuzo6H1AxpVl9fWFkYKJu4adlYmtiKPHj18yM9tIsBnxPfo0SMeLqSb78C//WgOGRM7GxNnR3cOJRMnc0RQR37zX9+CZuhoZG7xxoTH2AbVzt7E1tbF8bUTorGhs+HNIBQUFPjNBeIwQ5Aw8Dkb3nBUBBBg33TnfBAEP/OFQ3t8/zWZ82s4RPCfia2MTijLbIzgNv2GcAJhdPvsteS6F+B49X/G8guDy8MAbZiSJ73h5Pf1/8kP3nXFlkrJNVftiVWvfPEX51rDChuue9IcviLx1djMThz630S0GSxJBmNq3Z9kbm2jrpQ8/cEkmV7CJAlBfmL/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axis6 {
            get {
                return ResourceManager.GetString("axis6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cube {
            get {
                object obj = ResourceManager.GetObject("cube", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat {
            get {
                object obj = ResourceManager.GetObject("flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
